name: Deploy

on:
  push:
    branches:
      - master

jobs:
  built-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build
        run: |
          yarn --frozen-lockfile
          yarn build --modern

      - name: Test:unit
        run: yarn test:unit

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
